# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_windowrETsNU.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PyQt6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PyQt6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDockWidget,
    QFrame, QHBoxLayout, QLayout, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSpacerItem, QSpinBox, QStatusBar,
    QTabWidget, QToolBar, QToolBox, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(704, 598)
        self.actionLayer = QAction(MainWindow)
        self.actionLayer.setObjectName(u"actionLayer")
        self.actionDowanloadTiles = QAction(MainWindow)
        self.actionDowanloadTiles.setObjectName(u"actionDowanloadTiles")
        self.actionGeoTiffMaker = QAction(MainWindow)
        self.actionGeoTiffMaker.setObjectName(u"actionGeoTiffMaker")
        self.actionLocalTileDirectory = QAction(MainWindow)
        self.actionLocalTileDirectory.setObjectName(u"actionLocalTileDirectory")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionImportMarkers = QAction(MainWindow)
        self.actionImportMarkers.setObjectName(u"actionImportMarkers")
        self.actionImportAnnotation = QAction(MainWindow)
        self.actionImportAnnotation.setObjectName(u"actionImportAnnotation")
        self.actionDownloadElevation = QAction(MainWindow)
        self.actionDownloadElevation.setObjectName(u"actionDownloadElevation")
        self.actionHand = QAction(MainWindow)
        self.actionHand.setObjectName(u"actionHand")
        self.actionHand.setCheckable(True)
        self.actionHand.setChecked(False)
        self.actionHand.setEnabled(True)
        icon = QIcon()
        icon.addFile(u"../resources/icons/hand.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionHand.setIcon(icon)
        self.actionPath = QAction(MainWindow)
        self.actionPath.setObjectName(u"actionPath")
        self.actionPath.setCheckable(True)
        icon1 = QIcon()
        icon1.addFile(u"../resources/icons/pencil.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPath.setIcon(icon1)
        self.actionMarker = QAction(MainWindow)
        self.actionMarker.setObjectName(u"actionMarker")
        self.actionMarker.setCheckable(True)
        icon2 = QIcon()
        icon2.addFile(u"../resources/icons/marker.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionMarker.setIcon(icon2)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionImportLocalTiles = QAction(MainWindow)
        self.actionImportLocalTiles.setObjectName(u"actionImportLocalTiles")
        self.actionExportAnnotaion = QAction(MainWindow)
        self.actionExportAnnotaion.setObjectName(u"actionExportAnnotaion")
        self.actionExportMarker = QAction(MainWindow)
        self.actionExportMarker.setObjectName(u"actionExportMarker")
        self.actionXyzToLatLon = QAction(MainWindow)
        self.actionXyzToLatLon.setObjectName(u"actionXyzToLatLon")
        self.actionLatLonToXyz = QAction(MainWindow)
        self.actionLatLonToXyz.setObjectName(u"actionLatLonToXyz")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.widgetSearchBar = QWidget(self.widget)
        self.widgetSearchBar.setObjectName(u"widgetSearchBar")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSearchBar.sizePolicy().hasHeightForWidth())
        self.widgetSearchBar.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QHBoxLayout(self.widgetSearchBar)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.lineEditAddress = QLineEdit(self.widgetSearchBar)
        self.lineEditAddress.setObjectName(u"lineEditAddress")

        self.horizontalLayout_2.addWidget(self.lineEditAddress)

        self.lineEditLat = QLineEdit(self.widgetSearchBar)
        self.lineEditLat.setObjectName(u"lineEditLat")
        self.lineEditLat.setMaximumSize(QSize(200, 16777215))

        self.horizontalLayout_2.addWidget(self.lineEditLat)

        self.lineEditLon = QLineEdit(self.widgetSearchBar)
        self.lineEditLon.setObjectName(u"lineEditLon")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.lineEditLon.sizePolicy().hasHeightForWidth())
        self.lineEditLon.setSizePolicy(sizePolicy1)
        self.lineEditLon.setMaximumSize(QSize(200, 16777215))

        self.horizontalLayout_2.addWidget(self.lineEditLon)

        self.spinBoxZoom = QSpinBox(self.widgetSearchBar)
        self.spinBoxZoom.setObjectName(u"spinBoxZoom")
        self.spinBoxZoom.setMinimum(1)
        self.spinBoxZoom.setMaximum(19)
        self.spinBoxZoom.setValue(10)

        self.horizontalLayout_2.addWidget(self.spinBoxZoom)

        self.pushButtonSearch = QPushButton(self.widgetSearchBar)
        self.pushButtonSearch.setObjectName(u"pushButtonSearch")

        self.horizontalLayout_2.addWidget(self.pushButtonSearch)


        self.verticalLayout.addWidget(self.widgetSearchBar)

        self.widgetMap = QWidget(self.widget)
        self.widgetMap.setObjectName(u"widgetMap")
        self.mapLayout = QVBoxLayout(self.widgetMap)
        self.mapLayout.setObjectName(u"mapLayout")

        self.verticalLayout.addWidget(self.widgetMap)


        self.horizontalLayout.addWidget(self.widget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 704, 33))
        self.menubar.setNativeMenuBar(True)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuOpen = QMenu(self.menuFile)
        self.menuOpen.setObjectName(u"menuOpen")
        self.menuImport = QMenu(self.menuFile)
        self.menuImport.setObjectName(u"menuImport")
        self.menuExport = QMenu(self.menuFile)
        self.menuExport.setObjectName(u"menuExport")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.dockWidget = QDockWidget(MainWindow)
        self.dockWidget.setObjectName(u"dockWidget")
        self.dockWidget.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy2)
        self.verticalLayout_2 = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.tabWidget = QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy3)
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(Qt.TextElideMode.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabMaps = QWidget()
        self.tabMaps.setObjectName(u"tabMaps")
        sizePolicy2.setHeightForWidth(self.tabMaps.sizePolicy().hasHeightForWidth())
        self.tabMaps.setSizePolicy(sizePolicy2)
        self.verticalLayout_3 = QVBoxLayout(self.tabMaps)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.toolBox = QToolBox(self.tabMaps)
        self.toolBox.setObjectName(u"toolBox")
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setFrameShape(QFrame.Shape.NoFrame)
        self.toolBox.setFrameShadow(QFrame.Shadow.Plain)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setGeometry(QRect(0, 0, 98, 42))
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.verticalLayout_4 = QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.comboBoxTileServer = QComboBox(self.page)
        self.comboBoxTileServer.setObjectName(u"comboBoxTileServer")

        self.verticalLayout_4.addWidget(self.comboBoxTileServer)

        self.toolBox.addItem(self.page, u"Tile Servers")
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setGeometry(QRect(0, 0, 182, 116))
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.verticalLayout_6 = QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.checkBoxAnnotations = QCheckBox(self.page_2)
        self.checkBoxAnnotations.setObjectName(u"checkBoxAnnotations")
        self.checkBoxAnnotations.setAutoFillBackground(False)
        self.checkBoxAnnotations.setChecked(True)
        self.checkBoxAnnotations.setTristate(False)

        self.verticalLayout_6.addWidget(self.checkBoxAnnotations)

        self.checkBoxMarkers = QCheckBox(self.page_2)
        self.checkBoxMarkers.setObjectName(u"checkBoxMarkers")
        self.checkBoxMarkers.setChecked(True)

        self.verticalLayout_6.addWidget(self.checkBoxMarkers)

        self.checkBoxLocalTiles = QCheckBox(self.page_2)
        self.checkBoxLocalTiles.setObjectName(u"checkBoxLocalTiles")
        self.checkBoxLocalTiles.setChecked(True)

        self.verticalLayout_6.addWidget(self.checkBoxLocalTiles)

        self.checkBoxOnlineMap = QCheckBox(self.page_2)
        self.checkBoxOnlineMap.setObjectName(u"checkBoxOnlineMap")
        self.checkBoxOnlineMap.setChecked(True)

        self.verticalLayout_6.addWidget(self.checkBoxOnlineMap)

        self.toolBox.addItem(self.page_2, u"Layers")

        self.verticalLayout_3.addWidget(self.toolBox)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_3.addItem(self.verticalSpacer)

        self.tabWidget.addTab(self.tabMaps, "")
        self.tabAnnotations = QWidget()
        self.tabAnnotations.setObjectName(u"tabAnnotations")
        self.tabWidget.addTab(self.tabAnnotations, "")
        self.tabMarkers = QWidget()
        self.tabMarkers.setObjectName(u"tabMarkers")
        self.tabWidget.addTab(self.tabMarkers, "")

        self.verticalLayout_2.addWidget(self.tabWidget)

        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockWidget)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuImport.addAction(self.actionImportLocalTiles)
        self.menuImport.addAction(self.actionImportMarkers)
        self.menuImport.addAction(self.actionImportAnnotation)
        self.menuExport.addAction(self.actionExportMarker)
        self.menuExport.addAction(self.actionExportAnnotaion)
        self.menuTools.addAction(self.actionDowanloadTiles)
        self.menuTools.addAction(self.actionGeoTiffMaker)
        self.menuTools.addAction(self.actionDownloadElevation)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionXyzToLatLon)
        self.menuTools.addAction(self.actionLatLonToXyz)
        self.menuHelp.addAction(self.actionAbout)
        self.toolBar.addAction(self.actionHand)
        self.toolBar.addAction(self.actionPath)
        self.toolBar.addAction(self.actionMarker)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
        self.toolBox.layout().setSpacing(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionLayer.setText(QCoreApplication.translate("MainWindow", u"Layer", None))
        self.actionDowanloadTiles.setText(QCoreApplication.translate("MainWindow", u"Dowanload Tiles", None))
        self.actionGeoTiffMaker.setText(QCoreApplication.translate("MainWindow", u"GeoTiff Maker", None))
        self.actionLocalTileDirectory.setText(QCoreApplication.translate("MainWindow", u"Local Tile Directory", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionImportMarkers.setText(QCoreApplication.translate("MainWindow", u"Marker", None))
        self.actionImportAnnotation.setText(QCoreApplication.translate("MainWindow", u"Annotation", None))
        self.actionDownloadElevation.setText(QCoreApplication.translate("MainWindow", u"Download Elevation", None))
        self.actionHand.setText(QCoreApplication.translate("MainWindow", u"Hand", None))
        self.actionPath.setText(QCoreApplication.translate("MainWindow", u"Path", None))
#if QT_CONFIG(tooltip)
        self.actionPath.setToolTip(QCoreApplication.translate("MainWindow", u"Path", None))
#endif // QT_CONFIG(tooltip)
        self.actionMarker.setText(QCoreApplication.translate("MainWindow", u"Marker", None))
#if QT_CONFIG(tooltip)
        self.actionMarker.setToolTip(QCoreApplication.translate("MainWindow", u"Marker", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load", None))
        self.actionImportLocalTiles.setText(QCoreApplication.translate("MainWindow", u"Local Tiles", None))
        self.actionExportAnnotaion.setText(QCoreApplication.translate("MainWindow", u"Annotaion", None))
        self.actionExportMarker.setText(QCoreApplication.translate("MainWindow", u"Marker", None))
        self.actionXyzToLatLon.setText(QCoreApplication.translate("MainWindow", u"xyz to Lat-Lon", None))
        self.actionLatLonToXyz.setText(QCoreApplication.translate("MainWindow", u"Lat-Lon to xyz", None))
#if QT_CONFIG(accessibility)
        self.widgetSearchBar.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.lineEditAddress.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Address", None))
        self.lineEditLat.setInputMask("")
        self.lineEditLat.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Latitude", None))
        self.lineEditLon.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Longtitude", None))
        self.pushButtonSearch.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuOpen.setTitle(QCoreApplication.translate("MainWindow", u"Open", None))
        self.menuImport.setTitle(QCoreApplication.translate("MainWindow", u"Import", None))
        self.menuExport.setTitle(QCoreApplication.translate("MainWindow", u"Export", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
#if QT_CONFIG(tooltip)
        self.toolBar.setToolTip(QCoreApplication.translate("MainWindow", u"Hand", None))
#endif // QT_CONFIG(tooltip)
        self.dockWidget.setWindowTitle("")
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QCoreApplication.translate("MainWindow", u"Tile Servers", None))
        self.checkBoxAnnotations.setText(QCoreApplication.translate("MainWindow", u"Annotaions", None))
        self.checkBoxMarkers.setText(QCoreApplication.translate("MainWindow", u"Markers", None))
        self.checkBoxLocalTiles.setText(QCoreApplication.translate("MainWindow", u"Local Tiles", None))
        self.checkBoxOnlineMap.setText(QCoreApplication.translate("MainWindow", u"Online Map", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QCoreApplication.translate("MainWindow", u"Layers", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMaps), QCoreApplication.translate("MainWindow", u"Maps", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnnotations), QCoreApplication.translate("MainWindow", u"Annotations", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMarkers), QCoreApplication.translate("MainWindow", u"Markers", None))
    # retranslateUi

